### ISSUE TITLE
Add Instructions for Visual Studio Mac

### ISSUE THREAD

**Issue by kieran-osgood** [nopSolutions/nopCommerce-plugin-template-VS#5]
There are no instructions that guide where to add the template on Visual Studio Mac (Community, 2019, LocalInstall 8.0).
Does anyone know how to install this?

**Comment by skoshelev** [comment]
Hi @KieranO547. we won't change the instruction, because this information not provided by the [Microsoft documentation](https://docs.microsoft.com/ru-ru/visualstudio/ide/how-to-locate-and-organize-project-and-item-templates?view=vs-2019), but you may found the path for your "project template" folder in your VS settings(Tools > Options > Projects and Solutions > Locations)
